#!/bin/sh
# @intent Build nginx config at container start from mounted routes file + env (no build-time script).
set -eu

CONFIG_PATH=/etc/nginx/conf.d/thonnas.conf
ROUTES_FILE=/opt/thonnas-routes/routes.txt

# @intent Normalize INFRA_DOCKER_PROXY_MAX_BODY_SIZE (from thonnas-config internal) for nginx; default 500m
normalize_client_max_body() {
  _raw="${1:-500m}"
  _s=$(printf '%s' "$_raw" | tr -d '\r\n;#{}$`|' | sed 's/[mM][bB]$//')
  case "$_s" in
    '' | *[!0-9.kKmMgG]*) _s=500 ;;
  esac
  case "$_s" in
    *[kKmMgG]) printf '%s' "$_s" ;;
    *) printf '%sm' "$_s" ;;
  esac
}

MAX_BODY=$(normalize_client_max_body "${INFRA_DOCKER_PROXY_MAX_BODY_SIZE:-500m}")

> "$CONFIG_PATH"
# @intent One http-level directive for this include file: applies to all server {} blocks below (avoids duplicating per vhost + default_server)
printf 'client_max_body_size %s;\n' "$MAX_BODY" >> "$CONFIG_PATH"

render_server() {
  host="$1"
  upstream="$2"
  websocket="${3:-false}"

  if [ -z "${host}" ]; then
    return
  fi

  upstream_var="upstream_$(echo "$upstream" | tr ':-' '__')"

  # @intent Write server_name with printf so host never breaks the line (avoids nginx "not terminated by ;")
  {
    echo "server {"
    echo "  listen 80;"
    printf '  server_name %s;\n' "$host"
    # @intent Nginx default client_max_body_size is 1m; npm/Verdaccio publish sends tarball as JSON/base64 (large)
    echo "  client_max_body_size 500m;"
    echo "  resolver 127.0.0.11 valid=10s;"
    echo "  set \$${upstream_var} ${upstream};"
    echo "  location / {"
    echo "    proxy_pass http://\$${upstream_var};"
    echo "    proxy_set_header Host \$host;"
    echo "    proxy_set_header X-Real-IP \$remote_addr;"
    echo "    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
    echo "    proxy_set_header X-Forwarded-Proto \$scheme;"
    echo "    proxy_set_header X-Forwarded-Host \$host;"
    echo "    proxy_set_header X-Forwarded-Port \$server_port;"
    if [ "${websocket}" = "true" ]; then
      echo "    proxy_http_version 1.1;"
      echo "    proxy_set_header Upgrade \$http_upgrade;"
      echo "    proxy_set_header Connection \"upgrade\";"
      echo "    proxy_read_timeout 3600;"
    fi
    echo "  }"
    echo "}"
  } >> "$CONFIG_PATH"
}

# Read route list from mounted file (generated by e2e-build with literal hostnames; no env lookup).
# @intent Format: host|upstream|websocket per line. Strip CR and sanitize so nginx server_name is terminated by ";".
if [ -f "$ROUTES_FILE" ]; then
  _old_ifs="$IFS"
  while IFS= read -r line; do
    line="$(printf '%s' "$line" | tr -d '\r')"
    case "$line" in
      '#'*) ;;
      '') ;;
      *)
        IFS='|'
        set -- $line
        # @intent Strip newlines and nginx-sensitive chars (# comment; {} break directive parsing)
        host="$(printf '%s' "${1:-}" | tr -d '\r\n\t#{}' | sed 's/;.*//')"
        upstream="$(printf '%s' "${2:-}" | tr -d '\r\n\t')"
        ws="$(printf '%s' "${3:-}" | tr -d '\r\n\t')"
        IFS="$_old_ifs"
        if [ -n "$upstream" ] && [ -n "$host" ]; then
          render_server "$host" "$upstream" "$ws"
        fi
        ;;
    esac
  done < "$ROUTES_FILE"
  IFS="$_old_ifs"
else
  echo "[reverse-proxy] WARNING: $ROUTES_FILE not found. Run npm run e2e-build and ensure the routes file is mounted."
fi

cat <<'EOF' >> "$CONFIG_PATH"
server {
  listen 80 default_server;
  server_name _;
  return 502 "Reverse proxy route not configured\n";
}
EOF

nginx -t
echo "[reverse-proxy] client_max_body_size=${MAX_BODY} (from INFRA_DOCKER_PROXY_MAX_BODY_SIZE)"
echo "[reverse-proxy] Configuration rendered to ${CONFIG_PATH}"
exec nginx -g 'daemon off;'

