root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -mod=mod -o ./tmp/api-go ./cmd/server/main.go"
bin = "./tmp/api-go"
include_ext = ["go"]
exclude_dir = ["vendor", "bin", "coverage", "dist", "logs", ".git", "tmp"]
delay = 1000
poll = true
poll_interval = 1000

[log]
color = true
timestamp = true

[env]
GO_ENV = "development"

[watch]
paths = [
  "cmd",
  "internal",
]
